# Generated by Django 4.2.13 on 2024-05-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="room_id",
            field=models.CharField(max_length=50),
        ),
    ]
