# Generated by Django 5.0.6 on 2024-05-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_message_room_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
