# Generated by Django 5.0.6 on 2024-05-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_chatroom_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="expiration_duration",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
